id: IB3E7BC74
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:15:38.773870
last_modified: 2023-02-08 15:15:38.774036
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: zh
bases:
  60BA:
    base_file: 60BA.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
